
name: Create tagged release

on:
  push:
    tags:
      - 'v*'

jobs:
  create_release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      -
        name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

  build:
    runs-on: ubuntu-latest
    needs:
      - create_release
    steps:
      -
        name: Action Checkout
        uses: actions/checkout@v3
      -
        name: Setup Golang
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      -
        name: Test
        run: go test -v ./...
      -
        name: Build
        run: |
          mkdir output
          bash ./cmds/liter-server/build.sh
          cp ./cmds/liter-server/litermc.service ./output/litermc.service
      -
        name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      -
        name: Upload Release Assets
        uses: zyxkad/upload-release-asset-dir@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_dir: ./output
